### ISSUE TITLE
Reimplementation of method in category

### ISSUE THREAD

**Issue by a2** [seivan-archives/SHSegueBlocks#1]
Reimplementing `-prepareForSegue:sender:` in a bad idea because it bypasses any logic that UIViewController may perform in its own implementation. See pandamonia/BlocksKit#116.

**Comment by seivan** [comment]
This does bode a concern. Thanks for bringing it up.

**Comment by seivan** [comment]
First off, the category implementation doesn't get called if the user decides to implement it themselves. Say if you were to work on an older project that had that sprinkled over the code base. 

And unlike in https://github.com/pandamonia/BlocksKit/issues/116  where they class had this little nugget:

```
 To forward the message to the next responder, send the message to super (the superclass implementation); do not send the message directly to the next responder.
```

It's a damn if you do, and damned if you don't. I rather do this and avoid swizzle were I can avoid it, some stuff are unavoidable for it, I was happy to see this working fine (or the assumption of it working fine :-)  
I rather choose this path than hijacking (swizzling) the call. I'll keep an eye out on the SDK in case its changed in the future

```
The default implementation of this method does nothing. Your view controller overrides this method when it needs to pass relevant data to the new view controller. 
```

**Comment by seivan** [comment]
I'm going to close this off now. If a user faces a concern, implement the selector and message

```
SH_handlesBlockForSegue:
```

But again, doesn't seem to be a bubbling event call nor does the default implementation do anything. 
I'm going to close this.

**Comment by Ricardo1980** [comment]
Awesome!
Thanks for this library, it saves time and makes my apps more readable. I had the prepareForSegue problem with other libs, but I could also fix the problem with this lib. Thanks a lot.

**Comment by seivan** [comment]
No worries man. Much obliged. I got an update for it now to return IDs instead of UIViewControllers since you'd change them yourself.
